import type { MetadataRoute } from "next";

/**
 * Dynamic robots.txt: allow public waitlist routes, block API crawls, point to
 * the static sitemap generated by next-sitemap (`postbuild` → `public/sitemap.xml`).
 */

function trimTrailingSlash(url: string): string {
  return url.replace(/\/$/, "");
}

function getPublicOrigin(): string {
  const explicit = process.env.NEXT_PUBLIC_APP_URL?.trim();
  if (explicit) return trimTrailingSlash(explicit);
  const store = process.env.NEXT_PUBLIC_STORE_URL?.trim();
  if (store) return trimTrailingSlash(store);
  return "https://scentrev.com";
}

/** Block API routes from crawling; `/api/` covers all route handlers under `app/api`. */
const DISALLOW_PATHS = ["/api/", "/api"] as const;

export default function robots(): MetadataRoute.Robots {
  const origin = getPublicOrigin();
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [...DISALLOW_PATHS],
      },
    ],
    sitemap: `${origin}/sitemap.xml`,
    host: origin,
  };
}
