import type { Metadata } from "next";
import Link from "next/link";

const title = "Fragrance DNA card | ScentRev waitlist";
const description =
  "View a shared ScentRev scent-DNA card from the pilot — open the link to see notes, vibe, and what to try next.";

export const metadata: Metadata = {
  title,
  description,
  alternates: {
    canonical: "/share/scent-dna",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    title,
    description,
    type: "website",
    url: "/share/scent-dna",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

/**
 * Public landing for shared / copied links. OG image is generated by ``opengraph-image.tsx``.
 */
export default function ShareScentDnaPage() {
  return (
    <div className="min-h-[100dvh] bg-gradient-to-b from-[#FAF7F4] to-[#EDE6DF] px-6 py-16 text-[#1A1A1A]">
      <div className="mx-auto max-w-md text-center">
        <div className="mx-auto mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-[#1A1A1A] text-lg font-bold text-white shadow-lg">
          SR
        </div>
        <p className="text-[10px] font-bold uppercase tracking-[0.28em] text-[#B85A3A]">
          ScentRev waitlist
        </p>
        <h1 className="mt-3 font-display text-3xl font-bold tracking-tight">
          Fragrance <span className="text-[#B85A3A]">DNA</span>
        </h1>
        <p className="mt-4 text-sm leading-relaxed text-[#5C3A28]">
          Someone shared their pilot scent map from ScentRev. Join the waitlist to take the quiz,
          get matches, and build your own story-ready card.
        </p>
        <Link
          href="/"
          className="mt-8 inline-flex min-h-[48px] items-center justify-center rounded-xl bg-[#B85A3A] px-8 text-sm font-semibold text-white shadow-md transition hover:bg-[#a14f33]"
        >
          Join the waitlist
        </Link>
        <p className="mt-10 text-xs text-[#8A7A72]">
          India · micro samples · discovery-first
        </p>
      </div>
    </div>
  );
}
